# Generated by Django 3.1.1 on 2020-09-26 15:33

import datetime
from django.db import migrations, models
import view.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('page_id', models.CharField(default=0, max_length=100)),
                ('user', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insta_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Iupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=view.models.Iupload.file_change)),
                ('caption', models.CharField(max_length=250)),
                ('instagram', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('twitter', models.BooleanField(default=False)),
                ('users', models.CharField(default='None', max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 26, 21, 3, 4, 499849))),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('activated', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('twitter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndate', models.DateTimeField(default=datetime.datetime.now)),
                ('sdate', models.DateField(default=datetime.datetime.now)),
                ('stime', models.TimeField(default=datetime.datetime.now)),
                ('fid', models.IntegerField(default=0)),
                ('user', models.CharField(default='admin', max_length=50)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=200)),
                ('consumer_secret', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('access_token_secret', models.CharField(max_length=200)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('user', models.CharField(default='None', max_length=50)),
            ],
        ),
    ]
