# Generated by Django 3.0.8 on 2020-09-17 09:11

from django.db import migrations, models
import view.models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=view.models.Iupload.file_change)),
                ('caption', models.CharField(max_length=250)),
            ],
        ),
    ]
