# Generated by Django 3.1.1 on 2020-09-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_iupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='gender',
        ),
        migrations.AddField(
            model_name='pro',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pro',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pro',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
