# Generated by Django 3.1.1 on 2020-09-26 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20200926_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 21, 3, 44, 977314)),
        ),
    ]
