# Generated by Django 3.1.1 on 2020-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_auto_20200920_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='email',
        ),
        migrations.AlterField(
            model_name='pro',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
