# Generated by Django 3.1.1 on 2020-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20200920_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta',
            name='user',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
