# Generated by Django 3.1.1 on 2020-10-02 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20201002_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 18, 40, 1, 901129)),
        ),
    ]
