# Generated by Django 3.1.1 on 2020-10-02 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_auto_20201002_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='pro',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='pro',
            name='twitter',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 19, 24, 25, 416035)),
        ),
    ]
