# Generated by Django 3.1.1 on 2020-10-03 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0007_auto_20201002_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 22, 2, 39, 996769)),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='consumer_key',
            field=models.CharField(default='C9rcyMD5v6K9W0ZBcGFoGaaTW', max_length=200),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='consumer_secret',
            field=models.CharField(default='Yu7Kz3bAiItGP6H0SpU6CLSD5b1NnKqYHpiyLq1sbwAHTHx2ES', max_length=200),
        ),
    ]
