# Generated by Django 3.1.1 on 2020-10-04 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_auto_20201003_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=1500)),
                ('user', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 18, 36, 1, 914605)),
        ),
    ]
