# Generated by Django 3.1.1 on 2020-09-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='ndate',
        ),
        migrations.RemoveField(
            model_name='save',
            name='sdate',
        ),
    ]
