# Generated by Django 3.1.1 on 2020-10-04 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_auto_20201004_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 18, 36, 48, 224085)),
        ),
    ]
