# Generated by Django 3.1.1 on 2020-09-21 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_auto_20200921_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='ndate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='save',
            name='sdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='save',
            name='stime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='save',
            name='fid',
            field=models.IntegerField(default=0),
        ),
    ]
