# Generated by Django 3.1.1 on 2020-10-04 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_auto_20201004_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='iupload',
            name='linkd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 19, 55, 38, 724914)),
        ),
    ]
