# Generated by Django 3.1.1 on 2020-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_auto_20200921_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='user',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
