# Generated by Django 3.1.1 on 2020-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0011_save_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='iupload',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iupload',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iupload',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
