# Generated by Django 3.1.1 on 2020-09-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0012_auto_20200921_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
