# Generated by Django 3.1.1 on 2020-09-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0013_save_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
