# Generated by Django 3.1.1 on 2020-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0014_auto_20200923_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='page_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
