# Generated by Django 3.1.1 on 2020-12-15 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0015_auto_20201209_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 14, 38, 4, 129585)),
        ),
    ]
