# Generated by Django 3.1.1 on 2020-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0015_facebook_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
