# Generated by Django 3.1.1 on 2020-12-15 09:08

import datetime
from django.db import migrations, models
import view.models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0016_auto_20201215_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iupload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 14, 38, 57, 736718)),
        ),
        migrations.AlterField(
            model_name='iupload',
            name='file',
            field=models.FileField(default='null', upload_to=view.models.Iupload.file_change),
        ),
    ]
