# Generated by Django 3.1.1 on 2020-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0016_twitter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insta_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
