# Generated by Django 3.1.1 on 2020-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0017_insta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_data',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insta_data',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
